site_name: Knowledge Acquisition Agent
site_description: Documentation for the Knowledge Acquisition Agent project
site_author: Pablo
repo_url: https://github.com/costarotela/Knowledge_Acquisition
site_url: https://costarotela.github.io/Knowledge_Acquisition

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - Architecture:
    - Overview: architecture/overview.md
    - Components: architecture/components.md
    - Data Flow: architecture/data-flow.md
  - User Guide:
    - Getting Started: guide/getting-started.md
    - Configuration: guide/configuration.md
    - Examples: guide/examples.md
  - API Reference:
    - Scrapers: api/scrapers.md
    - Embeddings: api/embeddings.md
    - RAG: api/rag.md
  - Project Status:
    - Overview: status/overview.md
    - Roadmap: status/roadmap.md
    - Changelog: status/changelog.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - def_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/costarotela/Knowledge_Acquisition
  generator: false
