"""
Main configuration file for the knowledge acquisition system.
"""
api:
  # API keys will be loaded from environment variables
  openai_api_key: ${OPENAI_API_KEY}
  github_token: ${GITHUB_TOKEN}
  google_api_key: ${GOOGLE_API_KEY}

storage:
  vector_store_path: "./data/vector_store"
  knowledge_base_path: "./data/knowledge_base"
  cache_dir: "./data/cache"
  max_cache_size: 2048  # MB

processing:
  batch_size: 32
  max_workers: 4
  timeout: 300
  retry_attempts: 3
  use_gpu: true

monitoring:
  log_level: INFO
  log_file: "logs/knowledge_acquisition.log"
  enable_metrics: true
  metrics_port: 9090
  enable_tracing: false

agents:
  youtube_main:
    name: "YouTube Knowledge Agent"
    mode: collaborative
    enabled: true
    max_concurrent_tasks: 5
    task_timeout: 600
    retry_policy:
      max_attempts: 3
      backoff_factor: 2
    max_videos: 100
    download_path: "./data/downloads/youtube"
    supported_formats: ["mp4", "webm"]
    extract_captions: true

  web_research_main:
    name: "Web Research Agent"
    mode: collaborative
    enabled: true
    max_concurrent_tasks: 8
    task_timeout: 300
    retry_policy:
      max_attempts: 3
      backoff_factor: 1.5
    max_depth: 3
    max_pages: 50
    request_delay: 1.0
    excluded_domains:
      - "example.com"
      - "test.com"

  github_main:
    name: "GitHub Knowledge Agent"
    mode: collaborative
    enabled: true
    max_concurrent_tasks: 5
    task_timeout: 900
    retry_policy:
      max_attempts: 3
      backoff_factor: 2
    max_repos: 10
    max_files: 1000
    analyze_commits: true
    excluded_files:
      - "node_modules"
      - "__pycache__"
      - "*.pyc"
      - "*.pyo"
      - "*.pyd"
      - "*.so"

  rag_main:
    name: "RAG Knowledge Agent"
    mode: collaborative
    enabled: true
    max_concurrent_tasks: 10
    task_timeout: 300
    retry_policy:
      max_attempts: 2
      backoff_factor: 1.5
    model_name: "gpt-4"
    max_documents: 5
    temperature: 0.7
    max_tokens: 2000
