name: travel-agent
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - pip
  - conda:
    - pytest>=7.0.0
    - pytest-asyncio>=0.21.0
    - pytest-cov>=4.0.0
  - pip:
    - browser-use>=0.1.0
    - playwright>=1.40.0
    - pydantic>=2.0.0
    - aiohttp>=3.8.0
    - beautifulsoup4>=4.13.0
    - python-dotenv>=1.0.0
    - langchain>=0.1.0
    - langchain-openai>=0.0.2
